spring.application.name=Product_Service
server.port=${SERVER_PORT:8081}

#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_SET_URI}

logging.level.org.springframework.security=DEBUG

logging.level.org.hibernate.SQL=DEBUG
#app.auth-server-url=${AUTH_SERVER_URL}
