spring.application.name=Product_Service
server.port=${SERVER_PORT:8081}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:https://auth.stenhager.com}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_SET_URI:https://auth.stenhager.com/auth/jwks}
spring.security.oauth2.resourceserver.jwt.accepted-issuers=${JWT_ACCEPTED_ISSUERS:test-issuer,https://auth.stenhager.com}
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
server.forward-headers-strategy=framework
#app.auth-server-url=${AUTH_SERVER_URL}
