spring.application.name=Product_Service
server.port=${SERVER_PORT:8081}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_SET_URI:http://localhost:8080/auth/jwks}

logging.level.org.springframework.security=DEBUG

logging.level.org.hibernate.SQL=DEBUG
#app.auth-server-url=${AUTH_SERVER_URL}
